services:
  web:
    build: .
    container_name: sales_and_trading_web
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python create_superuser.py &&
             gunicorn sales_and_trading.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  celery:
    build: .
    container_name: sales_and_trading_celery
    command: celery -A sales_and_trading worker -l info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: sales_and_trading_db
    restart: always
    environment:
      POSTGRES_DB: sales_trading_db
      POSTGRES_USER: sales_trading_user
      POSTGRES_PASSWORD: sales_trading_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    container_name: sales_and_trading_redis
    ports:
      - "6379:6379"
    restart: always
